### ISSUE TITLE
invalid config

### ISSUE THREAD

**Issue by mgrachev** [reviewdog/action-yamllint#14]
I get the following error when running the action:
```
yamllint 1.26.3
invalid config: while scanning a quoted scalar
  in "<unicode string>", line 1, column 1:
    "{extends:
    ^
found unexpected end of stream
  in "<unicode string>", line 1, column 11:
    "{extends:
              ^
```

GH action:
```yaml
name: Linters
on: pull_request

jobs:
  yamllint:
    name: linters / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
          yamllint_flags: '-d "{extends: default, rules: {truthy: disable}}" .'
```

Link to failed action:
https://github.com/dotenv-linter/dotenv-linter/runs/3413087590?check_suite_focus=true
