### ISSUE TITLE
[example request] how to add a custom yamllint.yaml config file and have reviewdog parse it

### ISSUE THREAD

**Issue by SohamChakraborty** [reviewdog/action-yamllint#21]
Hi,

I am trying to add a custom `.yamllint.yaml` file. I am just using the relaxed configuration from https://yamllint.readthedocs.io/en/stable/configuration.html. And then I am doing this 

```
---
name: reviewdog
on: [pull_request]
jobs:
  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          yamllint_flags: 'src/.yamllint.yaml'


```

The custom file is present in `.github/src/.yamllint.yaml`. When the action runs it just stops at 

```
Requested labels: ubuntu-latest
Job defined at: repoX/.github/workflows/yamllint.yaml@refs/pull/10/merge
Waiting for a runner to pick up this job...
Job is waiting for a hosted runner to come online.
Job is about to start running on the hosted runner: Hosted Agent (hosted)
```

I am wondering if this is only possible with self hosted runner? If I don't use self hosted runner, how can I add a config file or pass certain arguments?

An example would be very helpful.
