### ISSUE TITLE
Allow specifying base docker image as an argument

### ISSUE THREAD

**Issue by ns-ksingh** [reviewdog/action-yamllint#43]
Since this action downloads `python:alpine` base image off DockerHub, at times it will randomly fail since we hit DockerHub ratelimits.

We have an internal artifactory which caches docker images and if the action accepted an argument to specify the image name this would fix the random failures.

```
- name: yamllint
   uses: reviewdog/action-yamllint@4e4ba96d03a0e12a0e71c29e5fef1db309d09201
   with:
     reporter: github-pr-review
     yamllint_flags: '. --no-warnings'
     docker_image: 'internal.docker-repo.example.com/python-alpine'
```

If no `docker_image` argument is provided, use the base image off DockerHub.
